# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='x',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
