# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_pricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
    ]
